on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-templates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check out data.table repository
        run: |
          git clone --depth=1 --single-branch https://github.com/rdatatable/data.table ../data.table
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install gettext
        run: sudo apt install -y gettext

      - name: Run 0_separa.R
        run: Rscript 0_separa.R

      - name: Print differences
        run: |
          git diff -I'^"POT-Creation-Date: ' --numstat pot/*.pot

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git diff -I'^"POT-Creation-Date: ' --numstat pot/*.pot | cut -f3 | xargs -r git add -v
          git add -v $(git ls-files -o --exclude-standard *.pot) || :
          git commit -vm 'Update translation templates' || echo "No changes to commit"

      - name: Push changes
        if: ${{ contains(fromJSON('["schedule", "workflow_dispatch"]'), github.event_name) }}
        run: |
          git push
