on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  update-templates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check out data.table repository
        uses: actions/checkout@v4
        with:
          repository: rdatatable/data.table
          path: ../data.table
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install gettext
        run: sudo apt install -y gettext

      - name: Run 0_separa.R
        run: Rscript 0_separa.R

      - name: See difference
        run: |
          git diff -I'^"POT-Creation-Date: ' --numstat pot/*.pot

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git diff -I'^"POT-Creation-Date: ' --numstat pot/*.pot | cut -f3 | xargs -r git add -v
          git add -v $(git ls-files -o --exclude-standard *.pot) || :
          git commit -m 'Data updated' || echo "No changes to commit"

      - name: Push changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          git push || echo "No commit to push"
