on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-templates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check out data.table repository
        run: |
          git clone --depth=1 --single-branch https://github.com/rdatatable/data.table ../data.table
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install gettext
        run: sudo apt install -y gettext

      - name: Run 0_separa.R
        run: Rscript 0_separa.R

      - name: Print differences
        run: |
          git diff -I'^"POT-Creation-Date: ' --numstat pot/*.pot

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git diff -I'^"POT-Creation-Date: ' --numstat pot/*.pot | cut -f3 | xargs -r git add -v
          git add -v $(git ls-files -o --exclude-standard *.pot) || :
          git commit -m 'Update translation templates' || echo "No changes to commit"
          git checkout .

      - name: Create pull request
        id: cpr
        if: ${{ contains(fromJSON('["schedule", "workflow_dispatch"]'), github.event_name) }}
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: pot/*.pot
          title: 'Update translation templates'
          assignees: rffontenelle

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
